## Code to create matrix and cache its inverse
## MakeCacheMatrix function creates a Matrix and 
## cacheSolve computes the inverse of the Matrix created by above function

## makeCacheMatrix function creates a matrix for this exercise

makeCacheMatrix <- function(x = matrix()) {
i <- NULL
set <- function(y){
  x <<- y
  i <<- NULL
}
get <- function()x
setInverse <- function(inverse) i <<- inverse
getInverse <- function() i 
list(set = set, get = get, 
     setInverse = setInverse, 
     getInverse = getInverse)
}


## This function created inverse matrix for the 
## matrix generated by the function makeCacheMatrix

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  i <- x$getInverse()
  if(!is.null(i)){
    message("getting cached data")
    return(i)
  }
  mat <- x$get()
  i <- solve(mat,...)
  x$setInverse(i)
  i
}

## Check
s <- matrix(rnorm(9),3,3)
s1 <- makeCacheMatrix(s)
cacheSolve(s1)
